[package]
name = "pizza"
version = "0.1.0"
edition = "2021"
target = "x86_64-unknown-linux-gnu"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sh-inline = "0.4.0"
